Ignore test untity files.
ARMmbed/mbed-cryptoauthlib pull request #6
Opened 2019-10-15 12:43 UTC by TaniaMirzin

Ignore untity files, as main application may use its own unity.
In case of MCCE, mbed-os compiles its own untity vesion and we need to ignore these files to avoid compilation errors.

2019-10-15 12:45 UTC, TaniaMirzin commented
@Patater

2019-10-15 15:17 UTC, Patater requested changes

2019-10-15 15:17 UTC, Patater commented on .mbedignore
> +cryptoauthlib/app/ip_protecton/
Please remove changing `cryptoauthlib/app` exclusions in commit "Ignore test untity files". The "Ignore test untity files" commit should only add the ignoring of Unity files.

2019-10-15 15:18 UTC, Patater commented
Please comment what testing was done with these changes.

2019-10-16 11:00 UTC, TaniaMirzin commented
@Patater Please review it, checked with mcce application.

2019-10-16 11:39 UTC, AndrzejKurek approved these changes

2019-10-16 12:25 UTC, Patater approved these changes
LGTM

2019-10-16 12:27 UTC, Patater commented
Oh, I noticed that this was made under your personal email address. I'll update during merge.

2019-10-16 12:31 UTC, Patater commented
Ah, you've disallowed maintainers to change this PR. Too bad.

2019-10-16 12:36 UTC, Patater commented
Closing in favor of https://github.com/ARMmbed/mbed-cryptoauthlib/pull/7

2019-10-16 12:45 UTC, closed without merging